### ISSUE TITLE
Increase the number of connection retries

### ISSUE THREAD

**Issue by jkpe** [fphammerle/switchbot-mqtt#36]
Hello,

Occasionally I will send the OPEN/CLOSE command to a SwitchBot Curtain and nothing happens. The logs show that it tries to connect and eventually fails. If I immediately try a second time it will work.

Would it be possible to increase the number of times switchbot-mqtt attempts to connect to the SwitchBot device?

I am using the Docker image fphammerle/switchbot-mqtt:0.6.0-armv6 on a Raspberry Pi 3B+. The Pi is sat directly next to both curtains. Here's an extract from my log when 1 curtain failed to open, I sent the OPEN command to a group in Home Assistant and 1 curtain opened but the other set of curtains did not.

Thank you for developing this ❤️

```
today at 14:22:54 2021-06-25T13:22:54+0000:DEBUG:switchbot_mqtt:received topic=homeassistant/cover/switchbot-curtain/D8:3E:**:**:**:**/set payload=b'OPEN'
today at 14:22:54 2021-06-25T13:22:54+0000:DEBUG:switchbot:Sending command to switchbot 570f**********
today at 14:22:54 2021-06-25T13:22:54+0000:DEBUG:switchbot:Connecting to Switchbot...
today at 14:22:55 2021-06-25T13:22:55+0000:DEBUG:switchbot:Failed connecting to Switchbot.
today at 14:22:55 Traceback (most recent call last):
today at 14:22:55   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/switchbot/__init__.py", line 51, in _connect
today at 14:22:55     self._device = bluepy.btle.Peripheral(self._mac,
today at 14:22:55   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 391, in __init__
today at 14:22:55     self._connect(deviceAddr, addrType, iface)
today at 14:22:55   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 439, in _connect
today at 14:22:55     raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
today at 14:22:55 bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral D8:3E:**:**:**:**, addr type: random
today at 14:22:55 2021-06-25T13:22:55+0000:WARNING:switchbot:Error talking to Switchbot.
today at 14:22:55 Traceback (most recent call last):
today at 14:22:55   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/switchbot/__init__.py", line 98, in _sendcommand
today at 14:22:55     self._connect()
today at 14:22:55   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/switchbot/__init__.py", line 51, in _connect
today at 14:22:55     self._device = bluepy.btle.Peripheral(self._mac,
today at 14:22:55   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 391, in __init__
today at 14:22:55     self._connect(deviceAddr, addrType, iface)
today at 14:22:55   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 439, in _connect
today at 14:22:55     raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
today at 14:22:55 bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral D8:3E:**:**:**:**, addr type: random
today at 14:22:55 2021-06-25T13:22:55+0000:WARNING:switchbot:Cannot connect to Switchbot. Retrying (remaining: 3)...
today at 14:22:55 2021-06-25T13:22:55+0000:DEBUG:switchbot:Sending command to switchbot 570f**********
today at 14:22:55 2021-06-25T13:22:55+0000:DEBUG:switchbot:Connecting to Switchbot...
today at 14:22:55 2021-06-25T13:22:55+0000:DEBUG:switchbot:Failed connecting to Switchbot.
today at 14:22:55 Traceback (most recent call last):
today at 14:22:55   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/switchbot/__init__.py", line 51, in _connect
today at 14:22:55     self._device = bluepy.btle.Peripheral(self._mac,
today at 14:22:55   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 391, in __init__
today at 14:22:55     self._connect(deviceAddr, addrType, iface)
today at 14:22:55   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 439, in _connect
today at 14:22:55     raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
today at 14:22:55 bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral D8:3E:**:**:**:**, addr type: random
today at 14:22:55 2021-06-25T13:22:55+0000:WARNING:switchbot:Error talking to Switchbot.
today at 14:22:55 Traceback (most recent call last):
today at 14:22:55   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/switchbot/__init__.py", line 98, in _sendcommand
today at 14:22:55     self._connect()
today at 14:22:55   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/switchbot/__init__.py", line 51, in _connect
today at 14:22:55     self._device = bluepy.btle.Peripheral(self._mac,
today at 14:22:55   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 391, in __init__
today at 14:22:55     self._connect(deviceAddr, addrType, iface)
today at 14:22:55   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 439, in _connect
today at 14:22:55     raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
today at 14:22:55 bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral D8:3E:**:**:**:**, addr type: random
today at 14:22:55 2021-06-25T13:22:55+0000:WARNING:switchbot:Cannot connect to Switchbot. Retrying (remaining: 2)...
today at 14:22:56 2021-06-25T13:22:56+0000:DEBUG:switchbot:Sending command to switchbot 570f**********
today at 14:22:56 2021-06-25T13:22:56+0000:DEBUG:switchbot:Connecting to Switchbot...
today at 14:22:56 2021-06-25T13:22:56+0000:DEBUG:switchbot:Failed connecting to Switchbot.
today at 14:22:56 Traceback (most recent call last):
today at 14:22:56   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/switchbot/__init__.py", line 51, in _connect
today at 14:22:56     self._device = bluepy.btle.Peripheral(self._mac,
today at 14:22:56   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 391, in __init__
today at 14:22:56     self._connect(deviceAddr, addrType, iface)
today at 14:22:56   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 439, in _connect
today at 14:22:56     raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
today at 14:22:56 bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral D8:3E:**:**:**:**, addr type: random
today at 14:22:56 2021-06-25T13:22:56+0000:WARNING:switchbot:Error talking to Switchbot.
today at 14:22:56 Traceback (most recent call last):
today at 14:22:56   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/switchbot/__init__.py", line 98, in _sendcommand
today at 14:22:56     self._connect()
today at 14:22:56   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/switchbot/__init__.py", line 51, in _connect
today at 14:22:56     self._device = bluepy.btle.Peripheral(self._mac,
today at 14:22:56   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 391, in __init__
today at 14:22:56     self._connect(deviceAddr, addrType, iface)
today at 14:22:56   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 439, in _connect
today at 14:22:56     raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
today at 14:22:56 bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral D8:3E:**:**:**:**, addr type: random
today at 14:22:56 2021-06-25T13:22:56+0000:WARNING:switchbot:Cannot connect to Switchbot. Retrying (remaining: 1)...
today at 14:22:56 2021-06-25T13:22:56+0000:DEBUG:switchbot:Sending command to switchbot 570f**********
today at 14:22:56 2021-06-25T13:22:56+0000:DEBUG:switchbot:Connecting to Switchbot...
today at 14:22:57 2021-06-25T13:22:57+0000:DEBUG:switchbot:Failed connecting to Switchbot.
today at 14:22:57 Traceback (most recent call last):
today at 14:22:57   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/switchbot/__init__.py", line 51, in _connect
today at 14:22:57     self._device = bluepy.btle.Peripheral(self._mac,
today at 14:22:57   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 391, in __init__
today at 14:22:57     self._connect(deviceAddr, addrType, iface)
today at 14:22:57   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 439, in _connect
today at 14:22:57     raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
today at 14:22:57 bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral D8:3E:**:**:**:**, addr type: random
today at 14:22:57 2021-06-25T13:22:57+0000:WARNING:switchbot:Error talking to Switchbot.
today at 14:22:57 Traceback (most recent call last):
today at 14:22:57   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/switchbot/__init__.py", line 98, in _sendcommand
today at 14:22:57     self._connect()
today at 14:22:57   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/switchbot/__init__.py", line 51, in _connect
today at 14:22:57     self._device = bluepy.btle.Peripheral(self._mac,
today at 14:22:57   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 391, in __init__
today at 14:22:57     self._connect(deviceAddr, addrType, iface)
today at 14:22:57   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 439, in _connect
today at 14:22:57     raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
today at 14:22:57 bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral D8:3E:**:**:**:**, addr type: random
today at 14:22:57 2021-06-25T13:22:57+0000:ERROR:switchbot:Switchbot communication failed. Stopping trying.
today at 14:22:57 NoneType: None
today at 14:22:57 2021-06-25T13:22:57+0000:ERROR:switchbot_mqtt:failed to open switchbot curtain D8:3E:**:**:**:**
today at 14:22:57 2021-06-25T13:22:57+0000:DEBUG:switchbot_mqtt:received topic=homeassistant/cover/switchbot-curtain/ED:D1:**:**:**:**/set payload=b'OPEN'
today at 14:22:57 2021-06-25T13:22:57+0000:DEBUG:switchbot:Sending command to switchbot 570f**********
today at 14:22:57 2021-06-25T13:22:57+0000:DEBUG:switchbot:Connecting to Switchbot...
today at 14:22:58 2021-06-25T13:22:58+0000:DEBUG:switchbot:Failed connecting to Switchbot.
today at 14:22:58 Traceback (most recent call last):
today at 14:22:58   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/switchbot/__init__.py", line 51, in _connect
today at 14:22:58     self._device = bluepy.btle.Peripheral(self._mac,
today at 14:22:58   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 391, in __init__
today at 14:22:58     self._connect(deviceAddr, addrType, iface)
today at 14:22:58   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 439, in _connect
today at 14:22:58     raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
today at 14:22:58 bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral ED:D1:**:**:**:**, addr type: random
today at 14:22:58 2021-06-25T13:22:58+0000:WARNING:switchbot:Error talking to Switchbot.
today at 14:22:58 Traceback (most recent call last):
today at 14:22:58   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/switchbot/__init__.py", line 98, in _sendcommand
today at 14:22:58     self._connect()
today at 14:22:58   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/switchbot/__init__.py", line 51, in _connect
today at 14:22:58     self._device = bluepy.btle.Peripheral(self._mac,
today at 14:22:58   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 391, in __init__
today at 14:22:58     self._connect(deviceAddr, addrType, iface)
today at 14:22:58   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 439, in _connect
today at 14:22:58     raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
today at 14:22:58 bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral ED:D1:**:**:**:**, addr type: random
today at 14:22:58 2021-06-25T13:22:58+0000:WARNING:switchbot:Cannot connect to Switchbot. Retrying (remaining: 3)...
today at 14:22:58 2021-06-25T13:22:58+0000:DEBUG:switchbot:Sending command to switchbot 570f**********
today at 14:22:58 2021-06-25T13:22:58+0000:DEBUG:switchbot:Connecting to Switchbot...
today at 14:22:58 2021-06-25T13:22:58+0000:DEBUG:switchbot:Failed connecting to Switchbot.
today at 14:22:58 Traceback (most recent call last):
today at 14:22:58   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/switchbot/__init__.py", line 51, in _connect
today at 14:22:58     self._device = bluepy.btle.Peripheral(self._mac,
today at 14:22:58   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 391, in __init__
today at 14:22:58     self._connect(deviceAddr, addrType, iface)
today at 14:22:58   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 439, in _connect
today at 14:22:58     raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
today at 14:22:58 bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral ED:D1:**:**:**:**, addr type: random
today at 14:22:58 2021-06-25T13:22:58+0000:WARNING:switchbot:Error talking to Switchbot.
today at 14:22:58 Traceback (most recent call last):
today at 14:22:58   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/switchbot/__init__.py", line 98, in _sendcommand
today at 14:22:58     self._connect()
today at 14:22:58   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/switchbot/__init__.py", line 51, in _connect
today at 14:22:58     self._device = bluepy.btle.Peripheral(self._mac,
today at 14:22:58   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 391, in __init__
today at 14:22:58     self._connect(deviceAddr, addrType, iface)
today at 14:22:58   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 439, in _connect
today at 14:22:58     raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
today at 14:22:58 bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral ED:D1:**:**:**:**, addr type: random
today at 14:22:58 2021-06-25T13:22:58+0000:WARNING:switchbot:Cannot connect to Switchbot. Retrying (remaining: 2)...
today at 14:22:59 2021-06-25T13:22:59+0000:DEBUG:switchbot:Sending command to switchbot 570f**********
today at 14:22:59 2021-06-25T13:22:59+0000:DEBUG:switchbot:Connecting to Switchbot...
today at 14:22:59 2021-06-25T13:22:59+0000:DEBUG:switchbot:Failed connecting to Switchbot.
today at 14:22:59 Traceback (most recent call last):
today at 14:22:59   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/switchbot/__init__.py", line 51, in _connect
today at 14:22:59     self._device = bluepy.btle.Peripheral(self._mac,
today at 14:22:59   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 391, in __init__
today at 14:22:59     self._connect(deviceAddr, addrType, iface)
today at 14:22:59   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 439, in _connect
today at 14:22:59     raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
today at 14:22:59 bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral ED:D1:**:**:**:**, addr type: random
today at 14:22:59 2021-06-25T13:22:59+0000:WARNING:switchbot:Error talking to Switchbot.
today at 14:22:59 Traceback (most recent call last):
today at 14:22:59   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/switchbot/__init__.py", line 98, in _sendcommand
today at 14:22:59     self._connect()
today at 14:22:59   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/switchbot/__init__.py", line 51, in _connect
today at 14:22:59     self._device = bluepy.btle.Peripheral(self._mac,
today at 14:22:59   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 391, in __init__
today at 14:22:59     self._connect(deviceAddr, addrType, iface)
today at 14:22:59   File "/switchbot-mqtt/.venv/lib/python3.8/site-packages/bluepy/btle.py", line 439, in _connect
today at 14:22:59     raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
today at 14:22:59 bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral ED:D1:**:**:**:**, addr type: random
today at 14:22:59 2021-06-25T13:22:59+0000:WARNING:switchbot:Cannot connect to Switchbot. Retrying (remaining: 1)...
today at 14:22:59 2021-06-25T13:22:59+0000:DEBUG:switchbot:Sending command to switchbot 570f**********
today at 14:22:59 2021-06-25T13:22:59+0000:DEBUG:switchbot:Connecting to Switchbot...
today at 14:23:00 2021-06-25T13:23:00+0000:DEBUG:switchbot:Connected to Switchbot.
today at 14:23:00 2021-06-25T13:23:00+0000:DEBUG:switchbot:Prepare to send
today at 14:23:01 2021-06-25T13:23:01+0000:DEBUG:switchbot:Sending command, 570f**********
today at 14:23:01 2021-06-25T13:23:01+0000:INFO:switchbot:Successfully sent command to Switchbot (MAC: ED:D1:**:**:**:**).
today at 14:23:01 2021-06-25T13:23:01+0000:DEBUG:switchbot:Disconnecting
today at 14:23:01 2021-06-25T13:23:01+0000:INFO:switchbot_mqtt:switchbot curtain ED:D1:**:**:**:** opening
today at 14:23:01 2021-06-25T13:23:01+0000:DEBUG:switchbot_mqtt:publishing topic=homeassistant/cover/switchbot-curtain/ED:D1:**:**:**:**/state payload=b'opening'
```

**Comment by fphammerle** [comment]
Hi, thanks for the detailed description and log!
(I edited your post to hide a part of the mac address for privacy, but I am afraid it's still visible in the post's history)

> Would it be possible to increase the number of times switchbot-mqtt attempts to connect to the SwitchBot device?

`SwitchbotDevice`'s constructor has a `retry_count` kwarg: https://github.com/Danielhiversen/pySwitchbot/blob/0.11.0/switchbot/__init__.py#L218

Makes sense to add an option / parameter to configure that number (default: 3)

I'll take a look when I find time. If anyone wants to contribute / add that options, please go ahead

**Comment by jkpe** [comment]
> I edited your post to hide a part of the mac addresses for privacy

Thank you.

I noticed that SwitchBot-MQTT-BLE-ESP32 tries connecting 60 times and tries sending the command 30 times before giving up:
https://github.com/devWaves/SwitchBot-MQTT-BLE-ESP32/blob/13c0940459210e54b0d6facde451f017e9bd0078/SwitchBot-BLE2MQTT-ESP32.ino#L364

**Comment by fphammerle** [comment]
@jkpe, @rickieyyy, could you retry with release `v0.7.0`?
I added a command-line parameter to change to number of retries:  `--retries`
